site_name: Monki documentation
site_url: http://monki.monomelodies.nl/docs/
repo_url: https://github.com/monomelodies/monki

pages:
- Home:
    - 'Quickstart': 'index.md'
- Usage:
    - 'Creating a simple API': 'simple.md'
    - 'Validating requests': 'validating.md'
    - 'Advanced topics': 'advanced.md'

copyright: Copyright &copy; 2015, <a href="http://www.monomelodies.nl/">Marijn Ophorst</a>




