site_name: Monki documentation
site_url: http://monki.monomelodies.nl/docs/
repo_url: https://github.com/monomelodies/monki

pages:
- Home:
    - 'User guide': 'index.md'

copyright: Copyright &copy; 2015, <a href="http://www.monomelodies.nl/">Marijn Ophorst</a>




