
DROP TABLE IF EXISTS twitter_user;
CREATE TABLE twitter_user (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(16) NOT NULL,
    password VARCHAR(32) NOT NULL,
    datecreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIME
);

DROP TABLE IF EXISTS twitter_tweet;
CREATE TABLE twitter_tweet (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    owner INTEGER NOT NULL REFERENCES twitter_user(id) ON DELETE CASCADE,
    content VARCHAR(140) NOT NULL,
    datecreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIME
);

